version: '3.8'

volumes:
  pgdata:

networks:
  pgdata_net:
    name: pgdata_net
    driver: bridge

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    networks:
    - pgdata_net
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgdataroot
      POSTGRES_USER: pgdatauser
      POSTGRES_DB: pgdata_db

  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin4
    ports:
      - 80:80
    networks:
      - pgdata_net
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: pgdataroot
      PGADMIN_DEFAULT_EMAIL: admin@admin.com